### api/articles/add/:userId    x3
POST http://localhost:3050/api/articles/add/64db8bc94eed2088a3745e77 HTTP/1.1
Content-Type: application/json

{
    "title": "Lorem ipsum dolor sit amet",
    "description": "Lorem ipsum dolor sit amet consectetur. Condimentum consectetur et urna maecenas. Sed.",
    "category": ["Branding", "Nouvelles"]
}

###
POST http://localhost:3050/api/articles/add/64db8bc94eed2088a3745e77 HTTP/1.1
Content-Type: application/json

{
    "title": "Lorem ipsum dolor sit amet consectetur. Velit sit elit blandit.",
    "description": "Lorem ipsum dolor sit amet consectetur. Integer cras eleifend pharetra vestibulum amet facilisis a.",
    "category": ["Branding", "Nouvelles"]
}

###
POST http://localhost:3050/api/articles/add/64db8bc94eed2088a3745e77 HTTP/1.1
Content-Type: application/json

{
    "title": "Lorem ipsum dolor sit amet consectetur. Rhoncus et massa.",
    "subtitle": "Lorem ipsum dolor sit amet consectetur. Rhoncus et massa",
    "description": "Lorem ipsum dolor sit amet consectetur. Aenean feugiat et massa eros aliquam. Pretium nunc.",
    "category": ["Branding", "Nouvelles"]
}


###
POST http://localhost:3050/api/articles/add/64db8bc94eed2088a3745e77 HTTP/1.1
Content-Type: application/json

{  
    "title": "Lorem ipsum dolor sit amet consectetur. Pretium eros.",
    "description": "Lorem ipsum dolor sit amet consectetur. Cras turpis adipiscing sit placerat in aenean euismod.",
    "category": ["Branding", "Nouvelles"]
}