version: "3.8"
services:
  mongodb:
    container_name: app-agence-aloha
    image: mongo
    restart: always
    volumes:
      - data:/data/db
      - ./data/db/data/db
  backend:
    build: ./backend
    ports:
      - "3050:3050"
    volumes:
      - logs:/app-agence-aloha/logs
      - ./backend:/app-agence-aloha
      - /app-agence-aloha/node_modules
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app-agence-aloha/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
