### AUTHENTIFICATION ROUTES

### api/auth/signup
POST http://localhost:3050/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "firstname": "Roxann",
    "lastname": "Meunier",
    "email": "alexandra1",
    "password": "1"
}

### api/auth/login
POST http://localhost:3050/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "alexandra1",
    "password": "1"
}

### POSTS ROUTES

### api/articles
# GET http://localhost:3050/api/articles/d HTTP/1.1
GET https://app-agence-aloha.vercel.app/api/articles/d HTTP/1.1

### api/articles
# GET http://localhost:3050/api/articles/d HTTP/1.1
GET http://localhost:3050/api/articles/d HTTP/1.1


### api/articles/:userId
GET http://localhost:3050/api/articles/64db8bc94eed2088a3745e77 HTTP/1.1

### api/articles/add/:userId
POST http://localhost:3050/api/articles/add/64db8bc94eed2088a3745e77 HTTP/1.1
Content-Type: application/json

{
    "title": "Branding et design",
    "description": "1",
    "category": ["Branding", "Nouvelles"]
}


### api/articles/update/:articleId
PUT http://localhost:3050/api/articles/update/64e12e52cef97e974b690990 HTTP/1.1
Content-Type: application/json

{
    "title": "Branding et design",
    "description": "2",
    "category": ["Branding", "Nouvelles"]
}

### api/articles/delete/:articleId
DELETE http://localhost:3050/api/articles/delete/64e12e52cef97e974b690990 HTTP/1.1
Content-Type: application/json


### QUESTIONS ROUTES

### api/questions/:userId
GET http://localhost:3050/api/questions/64db8bc94eed2088a3745e77 HTTP/1.1

### api/questions/add/:userId
POST http://localhost:3050/api/questions/add/64db8bc94eed2088a3745e77 HTTP/1.1
Content-Type: application/json

{
    "question": "Pourquoi faire affaire avec notre agence?",
    "answer": "Nous disposons des ressources et des méthodes les plus sophistiquées pour la préparation, la mise en oeuvre et l’analyse de vos projets. Nous vous offrons la paix d’esprit ainsi que la qualité garantie."
}

### api/questions/update/:questionId
PUT http://localhost:3050/api/questions/update/64dbacb3401784bc5b5f140e HTTP/1.1
Content-Type: application/json

{
    "title": "Branding et design",
    "description": "2",
    "category": ["Branding", "Nouvelles"]
}

### api/questions/delete/:questionId
DELETE http://localhost:3050/api/questions/delete/64dbacb3401784bc5b5f140e HTTP/1.1
Content-Type: application/json
