### AUTHENTIFICATION ROUTES

### api/auth/signup
POST http://localhost:3050/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "firstname": "Roxann",
    "lastname": "Meunier",
    "email": "alexandra1",
    "password": "1"
}

### api/auth/login
POST http://localhost:3050/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "alexandra1",
    "password": "1"
}

### POSTS ROUTES

### api/posts
GET http://localhost:3050/api/posts/d HTTP/1.1

### api/posts/:userId
GET http://localhost:3050/api/posts/64db8bc94eed2088a3745e77 HTTP/1.1

### api/posts/:userId/add
POST http://localhost:3050/api/posts/64db8bc94eed2088a3745e77/add HTTP/1.1
Content-Type: application/json

{
    "title": "Branding et design",
    "description": "1",
    "category": ["Branding", "Nouvelles"]
}

### api/posts/:postId/update
PUT http://localhost:3050/api/posts/64dbacb3401784bc5b5f140e/update HTTP/1.1
Content-Type: application/json

{
    "title": "Branding et design",
    "description": "2",
    "category": ["Branding", "Nouvelles"]
}

### api/posts/:postId/delete
DELETE http://localhost:3050/api/posts/64dbacb3401784bc5b5f140e/delete HTTP/1.1
Content-Type: application/json


### QUESTIONS ROUTES

### api/questions/:userId
GET http://localhost:3050/api/questions/64db8bc94eed2088a3745e77 HTTP/1.1

### api/questions/:userId/add
POST http://localhost:3050/api/questions/64db8bc94eed2088a3745e77/add HTTP/1.1
Content-Type: application/json

{
    "question": "Pourquoi faire affaire avec notre agence?",
    "answer": "Nous disposons des ressources et des méthodes les plus sophistiquées pour la préparation, la mise en oeuvre et l’analyse de vos projets. Nous vous offrons la paix d’esprit ainsi que la qualité garantie."
}

### api/questions/:questionId/update
PUT http://localhost:3050/api/questions/64dbacb3401784bc5b5f140e/update HTTP/1.1
Content-Type: application/json

{
    "title": "Branding et design",
    "description": "2",
    "category": ["Branding", "Nouvelles"]
}

### api/questions/:questionId/delete
DELETE http://localhost:3050/api/questions/64dbacb3401784bc5b5f140e/delete HTTP/1.1
Content-Type: application/json
